### PR TITLE
remove awkard icon placeholders (read description)

### PR DESCRIPTION
**Pull request by SrNightmare09**
IN th elanguages and tools heading, the icons had awkward looking placeholders whihc I have fixed, I have also kept the original version under comments in the file just in case you require them later!

### CODE REVIEW

**Review by SrNightmare09 — COMMENTED** [review]
add alt text to  tag

**Comment by blackcater** [comment]
> add alt text to  tag

Thanks for your PR.

Can you delete original lines?

https://github.com/blackcater/blackcater/pull/11/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R72-R77

**Comment by SrNightmare09** [comment]
> > add alt text to  tag
> 
> Thanks for your PR.
> 
> Can you delete original lines?
> 
> https://github.com/blackcater/blackcater/pull/11/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R72-R77

Sorry for not seeing your comment sooner, anyways, I ave removed all the original lines.

**Comment by blackcater** [comment]
> > > add alt text to  tag
> > 
> > 
> > Thanks for your PR.
> > Can you delete original lines?
> > [#11 (files)](https://github.com/blackcater/blackcater/pull/11/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R72-R77)
> 
> Sorry for not seeing your comment sooner, anyways, I ave removed all the original lines.

Thanks a lot.

**Pull request merged**
